id: A14243663
base_file: fBCC4.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 14:16:17.440458
  last_modified_at: 2022-06-17 14:16:17.440465
