id: A14243663
base_file: f2B4A.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 14:16:17.403987
  last_modified_at: 2022-06-17 14:16:17.404004
